# code: language=ansible
---
- name: Install grafana
  community.general.zypper:
    name:
      - grafana
    update_cache: true
    state: present

- name: Copy Grafana configuration in place
  ansible.builtin.template:
    src: "{{ grafana_config_file }}.j2"
    dest: "{{ config_dir }}/{{ grafana_config_file }}"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
    mode: 0644
  vars:
    conf: "{{ grafana_config }}"

- name: Enable grafana service
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: true
