# code: language=ansible
---
grafana_config_file: grafana.ini
config_dir: "/etc/grafana"
grafana_user: grafana
grafana_group: grafana
grafana_config:
  security:
    allow_embedding: true
  auth.anonymous:
    enabled: true
  server:
    root_url: "%(protocol)s://%(domain)s:%(http_port)s{{ grafana_sub_path }}/"
    serve_from_sub_path: true
