name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ansible-lint:
    name: Playbook linting
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v6
      